"""Audio migration

Revision ID: 198ab2ddba24
Revises: 35cfeee2a9fa
Create Date: 2026-02-07 17:36:26.658448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198ab2ddba24'
down_revision: Union[str, Sequence[str], None] = '35cfeee2a9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('google_drive_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'google_drive_id')
    # ### end Alembic commands ###
