"""Optional category attribute for documents

Revision ID: 3c166721b32c
Revises: 589f9fe3e0af
Create Date: 2026-02-06 10:23:49.257541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c166721b32c'
down_revision: Union[str, Sequence[str], None] = '589f9fe3e0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'category')
    # ### end Alembic commands ###
