"""Essay grading migration

Revision ID: 4ac39bb26e80
Revises: 198ab2ddba24
Create Date: 2026-02-09 16:26:48.313662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac39bb26e80'
down_revision: Union[str, Sequence[str], None] = '198ab2ddba24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('essay_content', sa.Text(), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('general_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essay_submissions_id'), 'essay_submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_essay_submissions_id'), table_name='essay_submissions')
    op.drop_table('essay_submissions')
    # ### end Alembic commands ###
