"""Add title column to documents

Revision ID: dfb3a62a3c67
Revises: 799d9bd0ea80
Create Date: 2026-03-30 18:37:51.335682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb3a62a3c67'
down_revision: Union[str, Sequence[str], None] = '799d9bd0ea80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###
